"""Customer book — load/save the demo customer base (JSON).

The demo book is generated by ``scripts/generate_loan_book.py``. In a real
deployment this layer would read core-banking + eCIB data instead.
"""
from __future__ import annotations

import json
from pathlib import Path

from app.agents.loans.models import CustomerProfile, Obligation

DEFAULT_BOOK_PATH = Path(__file__).resolve().parents[3] / "data" / "loans" / "customer_book.json"


def profile_from_dict(d: dict) -> CustomerProfile:
    return CustomerProfile(
        customer_id=d["customer_id"],
        name=d["name"],
        age=d["age"],
        bank=d["bank"],
        bank_code=d["bank_code"],
        city=d["city"],
        employment=d["employment"],
        net_monthly_income=d["net_monthly_income"],
        account_age_years=d["account_age_years"],
        salary_months_12=d["salary_months_12"],
        avg_balance_6m=d["avg_balance_6m"],
        previous_loan=d["previous_loan"],
        cheque_bounce_12m=d["cheque_bounce_12m"],
        ecib_dpd90_24m=d["ecib_dpd90_24m"],
        ecib_writeoff=d["ecib_writeoff"],
        obligations=[Obligation(**o) for o in d.get("obligations", [])],
        eom_balances=d.get("eom_balances", []),
        days_below_5k_30d=d.get("days_below_5k_30d", 0),
        salary_to_low_gap_days=d.get("salary_to_low_gap_days"),
    )


def profile_to_dict(p: CustomerProfile) -> dict:
    return {
        "customer_id": p.customer_id,
        "name": p.name,
        "age": p.age,
        "bank": p.bank,
        "bank_code": p.bank_code,
        "city": p.city,
        "employment": p.employment,
        "net_monthly_income": p.net_monthly_income,
        "account_age_years": p.account_age_years,
        "salary_months_12": p.salary_months_12,
        "avg_balance_6m": p.avg_balance_6m,
        "previous_loan": p.previous_loan,
        "cheque_bounce_12m": p.cheque_bounce_12m,
        "ecib_dpd90_24m": p.ecib_dpd90_24m,
        "ecib_writeoff": p.ecib_writeoff,
        "obligations": [{"label": o.label, "monthly_amount": o.monthly_amount} for o in p.obligations],
        "eom_balances": p.eom_balances,
        "days_below_5k_30d": p.days_below_5k_30d,
        "salary_to_low_gap_days": p.salary_to_low_gap_days,
    }


def load_book(path: str | Path | None = None) -> list[CustomerProfile]:
    path = Path(path) if path else DEFAULT_BOOK_PATH
    data = json.loads(path.read_text())
    return [profile_from_dict(d) for d in data["customers"]]


def save_book(customers: list[CustomerProfile], path: str | Path | None = None) -> Path:
    path = Path(path) if path else DEFAULT_BOOK_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(
        {"customers": [profile_to_dict(c) for c in customers]}, indent=1
    ))
    return path
